match:
  - regexp:
    - 1+
  - regexp:
    - 2+
    - z+
  - regexp:
    - 3+
    - \s+
  - regexp:
    - 4+
  - regexp:
    - 5+
  - regexp:
    - 6+
  - regexp:
    - 7+
  - regexp:
    - 8+
  - regexp:
    - 9+
  - regexp:
    - a+
  - regexp:
    - b+
  - regexp:
    - c+
  - regexp:
    - d+
  - regexp:
    - e+
  - regexp:
    - e+
  - regexp:
    - e+
  - regexp:
    - come.to.daddy
